services:
  - type: web
    name: whatsapp-server
    env: docker
    region: ohio
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4320
      - key: WHATSAPP_API_KEY
        sync: false
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"
